#!/bin/bash

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HYPR_DIR="$HOME/.config/hypr"

# Omarchy migrated Hyprland config from hyprlang (.conf) to Lua. Both trees are
# kept in this repo so a fleet can be mid-migration:
#
#   Lua      hypr/lua/*.lua          + hypr/lua/hosts/<hostname>.lua
#   hyprlang hyprland-overrides.conf + hosts/<hostname>.conf
#
# A machine is on Lua when ~/.config/hypr/hyprland.lua exists -- Hyprland
# prefers it over hyprland.conf. Install into whichever the machine uses.
# When changing a machine's scale, update BOTH host files until every machine
# has migrated.

install_lua() {
    local ENTRY="$HYPR_DIR/hyprland.lua"
    # dofile, not require: require() caches, and Hyprland's bootstrap only
    # clears package.loaded for its own prefixes, so a required entry point
    # would never re-run on `hyprctl reload`. init.lua clears the cache for the
    # submodules it requires. See the comment at the top of hypr/lua/init.lua.
    local REQUIRE_LINE='dofile(os.getenv("HOME") .. "/.config/supplement/init.lua")'
    local LINK="$HOME/.config/supplement"

    # Hyprland's package.path already covers ~/.config/?.lua, so symlinking the
    # module tree there is all the wiring the require needs.
    ln -sfn "$SCRIPT_DIR/hypr/lua" "$LINK"
    echo "Linked $LINK -> $SCRIPT_DIR/hypr/lua"

    # Required last so it overrides Omarchy's defaults, same as the .conf tree
    # being sourced last.
    if grep -Fq "$REQUIRE_LINE" "$ENTRY"; then
        echo "Require line already exists in $ENTRY"
    else
        echo "Adding require line to $ENTRY"
        printf '\n-- omarchy-supplement overrides (must come last).\n%s\n' "$REQUIRE_LINE" >>"$ENTRY"
    fi

    # Seed a host file so a new machine is tracked in git.
    local HOST HOSTFILE
    HOST="$(hostname)"
    HOSTFILE="$SCRIPT_DIR/hypr/lua/hosts/$HOST.lua"
    if [ ! -f "$HOSTFILE" ]; then
        echo "Creating hypr/lua/hosts/$HOST.lua from default (set the scale and commit it)"
        cp "$SCRIPT_DIR/hypr/lua/hosts/default.lua" "$HOSTFILE"
    fi

    render_monitors "$HOSTFILE"
}

# Monitor scale cannot be set from the supplement's own Lua modules: Omarchy's
# omarchy-hyprland-monitor-watch daemon polls every 2 seconds and force-reapplies
# the internal display's scale, reading it out of ~/.config/hypr/monitors.lua
# with sed:
#
#   sed -n 's/^local omarchy_monitor_scale = //p' ~/.config/hypr/monitors.lua
#
# and falling back to a hardcoded 2 when that isn't a bare number -- which is
# what the stock `= "auto"` does. So an hl.monitor rule from anywhere else is
# reverted within seconds. Render that file from the host file instead, keeping
# the exact line format the daemon's sed expects.
render_monitors() {
    local HOSTFILE="$1"
    local TARGET="$HYPR_DIR/monitors.lua"
    local SCALE GDK_SCALE

    if ! command -v lua >/dev/null 2>&1; then
        echo "lua not found; cannot read $HOSTFILE. Skipping monitor scale." >&2
        return 0
    fi

    SCALE="$(lua -e "print(assert(dofile('$HOSTFILE')).scale)")"
    GDK_SCALE="$(lua -e "print(assert(dofile('$HOSTFILE')).gdk_scale or 1)")"

    # The daemon's valid_scale() only accepts a bare number.
    if ! [[ $SCALE =~ ^[0-9]+([.][0-9]+)?$ ]]; then
        echo "Invalid scale '$SCALE' in $HOSTFILE (must be a bare number)." >&2
        return 1
    fi

    [ -f "$TARGET" ] && [ ! -f "$TARGET.omarchy-orig" ] && cp "$TARGET" "$TARGET.omarchy-orig"

    cat >"$TARGET" <<EOF
-- GENERATED by omarchy-supplement/install-hyprland-overrides.sh -- do not edit.
-- Source of truth: omarchy-supplement/hypr/lua/hosts/$(hostname).lua
-- Change the scale there and re-run ./install-hyprland-overrides.sh.
--
-- This file must keep the \`local omarchy_monitor_scale = <number>\` line in
-- exactly this shape: omarchy-hyprland-monitor-clamshell greps it with sed
-- every 2 seconds to reapply the internal display's scale, and falls back to a
-- hardcoded 2 if it can't parse a bare number there.

local omarchy_gdk_scale = $GDK_SCALE
local omarchy_monitor_scale = $SCALE

hl.env("GDK_SCALE", tostring(omarchy_gdk_scale))
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = omarchy_monitor_scale })
EOF

    echo "Rendered $TARGET (scale $SCALE, GDK_SCALE $GDK_SCALE)"
}

install_conf() {
    local ENTRY="$HYPR_DIR/hyprland.conf"
    local OVERRIDES_CONFIG="$SCRIPT_DIR/hyprland-overrides.conf"
    local SOURCE_LINE="source = $OVERRIDES_CONFIG"

    if [ ! -f "$OVERRIDES_CONFIG" ]; then
        echo "Overrides config not found at $OVERRIDES_CONFIG"
        exit 1
    fi

    if grep -Fxq "$SOURCE_LINE" "$ENTRY"; then
        echo "Source line already exists in $ENTRY"
    else
        echo "Adding source line to $ENTRY"
        echo "" >>"$ENTRY"
        echo "$SOURCE_LINE" >>"$ENTRY"
        echo "Source line added successfully"
    fi

    # Select the per-machine monitor/scale file by hostname and symlink it to the
    # path sourced by hyprland-overrides.conf. Per-host files live in hosts/ and
    # are tracked in git; a new machine is seeded from hosts/default.conf.
    local LOCAL_MONITORS HOST HOSTFILE
    LOCAL_MONITORS="$HYPR_DIR/monitors.local.conf"
    HOST="$(hostname)"
    HOSTFILE="$SCRIPT_DIR/hosts/$HOST.conf"
    if [ ! -f "$HOSTFILE" ]; then
        echo "Creating hosts/$HOST.conf from default (set MONSCALE and commit it)"
        cp "$SCRIPT_DIR/hosts/default.conf" "$HOSTFILE"
    fi
    ln -sf "$HOSTFILE" "$LOCAL_MONITORS"
}

if [ -f "$HYPR_DIR/hyprland.lua" ]; then
    echo "Detected Lua Hyprland config."
    install_lua
elif [ -f "$HYPR_DIR/hyprland.conf" ]; then
    echo "Detected hyprlang (.conf) Hyprland config."
    install_conf
else
    echo "Hyprland config not found in $HYPR_DIR"
    echo "Please install hyprland first"
    exit 1
fi

echo "Hyprland overrides setup complete!"
