#!/bin/bash

set -euo pipefail

# Make `fresh` (fresh-editor: a terminal text editor with multi-cursor support)
# the default editor for the whole Wayland/uwsm session, so TUIs like aerc open
# compose buffers in it instead of Omarchy's default (nvim).
#
# Why the session environment and not hypr/envs.conf: apps are launched via
# `uwsm app` (terminals, walker, keybinds), so they inherit the *systemd user*
# environment that uwsm populates -- that value wins over Hyprland's `env =`
# directives. So the editor must be set here to take effect.

EDITOR_CMD="${EDITOR_CMD:-fresh}"

# Install fresh-editor (AUR) unless another editor command was requested.
if [ "$EDITOR_CMD" = "fresh" ]; then
  if pacman -Qi fresh-editor-bin &>/dev/null; then
    echo "fresh-editor already installed."
  else
    yay -S --noconfirm --needed fresh-editor-bin
  fi
fi

# ── Omarchy's own editor indirection ─────────────────────────────────────────
# Do this FIRST and unconditionally -- on Omarchy 4 it is the step that does
# the real work. There the session default is
# `EDITOR="omarchy-launch-editor --inline"`, and that launcher reads this state
# file (falling back to nvim when it is absent), so writing it redirects
# $EDITOR, the SUPER+SHIFT+N keybind and `omarchy default editor` in one go.
# `fresh` is already on the launcher's inline whitelist, so it opens in the
# calling terminal instead of spawning a window.
#
# We write the file directly because omarchy-default-editor rejects `fresh` as
# an argument (its case list predates fresh-editor).
OMARCHY_EDITOR_STATE="$HOME/.local/state/omarchy/defaults/editor"
mkdir -p "$(dirname "$OMARCHY_EDITOR_STATE")"
printf '%s\n' "$EDITOR_CMD" >"$OMARCHY_EDITOR_STATE"
echo "Omarchy default editor set to '$EDITOR_CMD' (SUPER+SHIFT+N, omarchy-launch-editor)."

# ── Session environment (EDITOR / VISUAL) ────────────────────────────────────
# uwsm sources, in increasing priority, <dir>/uwsm/env and <dir>/uwsm/env.d/*
# for every XDG data and config dir, so a drop-in under ~/.config/uwsm/env.d/
# is the last thing loaded and beats Omarchy's /usr/share/uwsm/env.d/10-omarchy.
# That drop-in dir is the supported override point on Omarchy 4.
#
# The older single ~/.config/uwsm/default file is still sourced when it exists,
# but Omarchy no longer creates it -- so the previous `[ ! -f ]` guard here
# skipped this whole step (exit 0, no failure recorded) on every current
# install, leaving EDITOR at Omarchy's default and VISUAL unset entirely.
# Detect which layout the machine uses instead of assuming the legacy one.
UWSM_LEGACY_DEFAULT="$HOME/.config/uwsm/default"
if [ -f "$UWSM_LEGACY_DEFAULT" ]; then
  # Legacy install: keep editing the file the machine already has, replacing an
  # existing export rather than appending duplicates on every re-run.
  set_export() {
    local var="$1" val="$2"
    if grep -qE "^export ${var}=" "$UWSM_LEGACY_DEFAULT"; then
      sed -i "s|^export ${var}=.*|export ${var}=${val}|" "$UWSM_LEGACY_DEFAULT"
    else
      printf 'export %s=%s\n' "$var" "$val" >>"$UWSM_LEGACY_DEFAULT"
    fi
  }
  set_export EDITOR "$EDITOR_CMD"
  set_export VISUAL "$EDITOR_CMD"
  UWSM_TARGET="$UWSM_LEGACY_DEFAULT"
else
  # Current Omarchy: own one generated drop-in outright, so re-runs overwrite it
  # instead of having to parse back what a previous run wrote.
  UWSM_TARGET="$HOME/.config/uwsm/env.d/50-supplement-editor"
  mkdir -p "$(dirname "$UWSM_TARGET")"
  cat >"$UWSM_TARGET" <<EOF
# GENERATED by omarchy-supplement/install-editor.sh -- do not edit.
# Sourced by uwsm after /usr/share/uwsm/env.d/10-omarchy, so these win over the
# Omarchy session defaults. Changes require a session restart to take effect.
export EDITOR=$EDITOR_CMD
export VISUAL=$EDITOR_CMD
EOF
fi

# Apply to the running session too, so it takes effect without a relog. Already
# open apps keep their old env until restarted.
if command -v systemctl &>/dev/null; then
  systemctl --user set-environment EDITOR="$EDITOR_CMD" VISUAL="$EDITOR_CMD" 2>/dev/null || true
fi

echo "Default editor set to '$EDITOR_CMD' (EDITOR + VISUAL) in $UWSM_TARGET."
echo "Restart aerc / your terminal to pick it up."
